#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
import sys

from sigil.__main__ import main

if __name__ == "__main__":
    sys.argv[0] = sys.argv[0].removesuffix(".exe")
    # your modifications here
    sys.exit(main())
